# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
##ZSH_THEME="robbyrussell"
##ZSH_THEME="bira"
##ZSH_THEME="kardan"
ZSH_THEME="steeef"
##ZSH_THEME="muse"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
#DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
##plugins=(git git-extras git-flow composer nodejs npm phing)

##plugins=(git git-extras git-flow composer phing vagrant)
plugins=(git git-extras git-flow composer phing vagrant ansible gulp npm ipfs ubuntu tmux laravel)
source $ZSH/oh-my-zsh.sh

# User configuration

export PATH="/home/uhk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/uhk/Projects/depot_tools:/home/uhk/bin/phpstorm/bin"
# export MANPATH="/usr/local/man:$MANPATH"
export PATH="/home/uhk/.composer/vendor/bin:$PATH"
export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
alias zshconfig="editor ~/.zshrc"
## alias ohmyzsh="nano ~/.oh-my-zsh"
## alias sshpizza='ssh -i ~/.ssh/uhk-combine-rsa uhk@dev.netimage.dk'
## alias sshqnap='ssh -i ~/.ssh/ulrikkold-personal-rsa admin@qnap219p'
alias vpntortilla='sudo openvpn --askpass ~/.ssh/openvpn.pass --config ~/openvpn/NetImage-uhk.conf'
alias fullupgrade='sudo apt-get update && sudo apt-get dist-upgrade'
alias safeupgrade='sudo apt-get update && sudo apt-get upgrade'
alias ssh='ssh -A'
alias currtime='while sleep 1;do tput sc;tput cup 0 $(($(tput cols)-11));echo -e "\e[31m`date +%r`\e[39m";tput rc;done &'

## To avoid conflicts with graphicsmagick (named gm)
alias gme='git merge'
unalias gm

alias gst='git status -sb'

alias phpv5='sudo a2dismod php7.0 ; sudo a2enmod php5.6 ; sudo service apache2 restart ; echo 1 | sudo update-alternatives --config php'
alias phpv7='sudo a2dismod php5.6 ; sudo a2enmod php7.0 ; sudo service apache2 restart ; echo 2 | sudo update-alternatives --config php'

## I don't use NodeJS or nvm at the moment.
##export NVM_DIR="/home/uhk/.nvm"
##[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
##nvm use 0.10
#

fpath=(~/.zsh/completion $fpath)

autoload -Uz compinit && compinit -i

. ~/z/z.sh


if [ -x /usr/games/cowsay -a -x /usr/games/fortune -a -x /usr/games/lolcat ]; then
    fortune -sc | cowsay | lolcat
fi

export SLACK_TOKEN=''
